language: android

android:
  components:
    - extra-google-m2repository
    - extra-android-m2repository
    - platform-tools
    - build-tools-27.0.3
    - android-26

script:
  - echo -en 'travis_fold:start:script.gradle_build_carinfo\\r'
  - cd carinfo && bash ../gradlew build; cd ..
  - echo -en 'travis_fold:end:script.gradle_build_carinfo\\r'
  - echo -en 'travis_fold:start:script.gradle_build_screenmirroring\\r'
  - cd screenmirroring && bash ../gradlew build; cd ..
  - echo -en 'travis_fold:end:script.gradle_build_screenmirroring\\r'
